### ISSUE TITLE
Servers Broken

### ISSUE THREAD

**Issue by walksanatora** [walksanatora/HexxyTestPack#2]
the server hexxytest.hexxy.media is down. awaiting @Chloetax 's response.
yes this is a desperate attempt to circumvent discord Do Not Disturb

**Comment by Twisted-Code** [comment]
You should probably close this. Especially since I think I'm going to start listing the actual bugs in the pack. That way we can figure out (for instance):
A. Who to report them to and
B. When they get fixed upstream
